name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 8.2

      - name: Build files
        run: php generator.php 1> /dev/null

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ids.txt
          path: release/ids.txt
